### ISSUE TITLE
Valid JSON?

### ISSUE THREAD

**Issue by spenserkuroda** [gdherbert/DataPillager#10]
I'm having an issue with extracting a particular service from NOAA.  (https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/wwa_meteoceanhydro_longduration_hazards_time/MapServer)

It seems to catch an error in the if-else statement starting on line 349 where it checks the JSON for "error".  

```
service_call = urllib2.urlopen(service_endpoint + '?f=json' + tokenstring).read()
if service_call and (service_call.find('error') == -1):
    service_layer_info = json.loads(service_call, strict=False)
else:
    raise Exception("'service_call' failed to access {0}".format(service_endpoint))
```
It drops to the else statement on lines 351:2.  I validated the JSON with JSLint by saving the JSON from service_call to a txt file, but seems to be valid.  I also looked at the JSON using the url that the service call would be with the service I'm using.  I've also tried using other services and they seem to be fine.  I am able to bypass this error by commenting out the raise statement and adding in a json.loads() in the else clause.

Is there another way around this issue?  Would it be a poor decision to skip the error check?

**Comment by spenserkuroda** [comment]
A possible reason why this may be going to the else statement is that there is a sentence as part of the JSON response that includes the word "errors."  

It was suggested to me that `service_call.find('error') == -1` may be too generic and may need make the search more specific or parse the data before searching for errors.

**Comment by spenserkuroda** [comment]
I think a good workaround could be as simple as changing Line 351 `service_call.find('error') == -1` to `service_call.find('"error":') == -1`  since the JSON error looks to just be a key:value pair.  This works for me when in terms of getting the REST service extraction to work with the service I linked above.

**Comment by gdherbert** [comment]
I initially thought this was addressed already, but I see the issue and will include a fix in the next update
