### ISSUE TITLE
Reoccuring named layers overwritten during extraction

### ISSUE THREAD

**Issue by spenserkuroda** [gdherbert/DataPillager#11]
With the REST service I'm using (https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/wwa_meteoceanhydro_longduration_hazards_time/MapServer)  there layers which have reoccurring names which are grouped names.  To get around this I extracted the id from the parentLayer group/dictionary and used that in the naming of the extracted files.  

**Original at line 423:**
```
service_name = service_info.get('name')
# clean up the service name (remove invalid characters)
service_name_cl = service_name.encode('ascii', 'ignore') # strip any non-ascii characters that may cause an issue
service_name_cl = arcpy.ValidateTableName(service_name_cl, output_workspace) # remove any other problematic characters
##output_msg("'{0}' will be stashed as '{1}'".format(service_name, service_name_cl))
info_filename = service_name_cl + "_info.txt"
info_file = os.path.join(output_folder, info_filename)

```

**From line 423, here are the changes I made:**

```
service_name = service_info.get('name')
service_id_dict = service_info.get('parentLayer')
service_id = str(service_id_dict[u'id'])
# clean up the service name (remove invalid characters)
service_name_cl = service_name.encode('ascii', 'ignore') # strip any non-ascii characters that may cause an issue
service_name_cl = arcpy.ValidateTableName(service_name_cl, output_workspace) # remove any other problematic characters
service_id_cl = service_id.encode('ascii', 'ignore') # strip any non-ascii characters that may cause an issue
service_id_cl = arcpy.ValidateTableName(service_id_cl, output_workspace)  # remove any other problematic characters
##output_msg("'{0}' will be stashed as '{1}'".format(service_name, service_name_cl))
info_filename = service_name_cl + '_' + service_id_cl + "_info.txt"
```

I also altered the variables for the names on lines 520, 531, 533, 553, and 555.

If you implement this change, I'm not sure if you would need more conditional statements to check the grouped layer like earlier in the script, but this is how I got it to work.

Thanks for providing this tool openly, it's been a great help.

**Comment by gdherbert** [comment]
That workaround seems reasonable, you could also use the id of the service rather than the parent. While taking a look at the dataset you reference I notice that there is also a chance of having too long a file name with extremely long service names, so i will try to put something together that can handle both of those cases (duplicate service name and long names)

**Comment by gdherbert** [comment]
Pushed an update that handles long names and prevents overwriting existing layers.
