### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by erikfriesen** [gdherbert/DataPillager#7]
Tool returns ERROR 000206 when run. Input parameters attached as an image. Full dialog text with error message below.

--------------Output--------------------

Executing: DataServicePillager2 https://services2.arcgis.com/LgK9DpUhNjdU0HLy/arcgis/rest/services/cadastral1-14-15/FeatureServer/0 "\cortez-adsvr02\RedirectedFolders\efriesen\My Documents\PA\parcels.gdb" 5 5 # # # #
Start Time: Fri May 13 10:23:47 2016
Running script DataServicePillager2...
Error
RuntimeError: Object: Error in getting parameter as text
 on line 218
Executing: JSONToFeatures "\cortez-adsvr02\RedirectedFolders\efriesen\My Documents\PA\washington parcels\cadastral1_14_15_0.json" "\cortez-adsvr02\RedirectedFolders\efriesen\My Documents\PA\washington parcels\cadastral1_14_15_0.shp"
Start Time: Fri May 13 10:08:15 2016
ERROR 000206: Cannot create FeatureClass '\cortez-adsvr02\RedirectedFolders\efriesen\My Documents\PA\washington parcels\cadastral1_14_15_0.shp'. The workspace is not connected.
Failed to execute (JSONToFeatures).
Failed at Fri May 13 10:08:19 2016 (Elapsed Time: 4.29 seconds)
Plunderin' done, in 0:00:00.004000
Completed script DataServicePillager2...
Failed to execute (DataServicePillager2).
Failed at Fri May 13 10:23:47 2016 (Elapsed Time: 0.15 seconds)

-------------/Output--------------------

![input](https://cloud.githubusercontent.com/assets/1487525/15252785/29ec13ae-18f5-11e6-800d-2dcfb23b7d2f.PNG)

**Comment by gdherbert** [comment]
Apologies, I never got a notification on this. I think this error is because a UNC path was entered and it is getting mangled later on.

**Comment by gdherbert** [comment]
I am unable to replicate this using a UNC path for folder or gdb output.
