### ISSUE TITLE
Getting an error when adding User and Password on protected service

### ISSUE THREAD

**Issue by jclemis** [gdherbert/DataPillager#8]
Getting the following error when adding User and Password on protected service
Running script DataServicePillager2...
ERROR: No JSON object could be decoded
Plunderin' done, in 0:00:00.070000
Completed script DataServicePillager2...
Failed to execute (DataServicePillager2).
Failed at Wed Jul 19 16:35:09 2017 (Elapsed Time: 0.11 seconds)
Not sure if I am missing something. It works when I unprotect the service

**Comment by gdherbert** [comment]
It sounds like it is failing to authenticate. Is this a service that you could share some details about for debugging? Where is it hosted?

**Comment by gdherbert** [comment]
Updated to fix issue with authentication error on non standard web adaptor name, also tested with AGO.
