### ISSUE TITLE
No Parameter

### ISSUE THREAD

**Issue by sifatid** [gdherbert/DataPillager#9]
Hi, I tried adding the script to Arcmap toolbox and when I tried it out, there seems to be no link to the script parameters. I'm new to scripts and arc. Thank you.

**Comment by gdherbert** [comment]
When you clone/download the repo it includes an Esri toolbox with the tool set up with parameters. Be aware that you may need to update the source path to point to the script location. Once linked, you can import the script and copy/paste it to another toolbox. 
If you add the script to a different toolbox you will have to manually set up the parameters. The arcpy parameter arguments appear under the main() function.

**Comment by gdherbert** [comment]
Updated script to include hints for parameter entry in main()
